
[driver]
    binary = "/usr/local/bin/chromedriver"
    [driver.options]
         args = [
            "--window-size=1920,1080",
            "--disable-gpu",
            "--headless",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--mute-audio"
         ]
